Repository dnd-side-project/dnd-7th-2-backend, pull requests merged in 2022-08, with the labels that each got.

#18 feature/#17 이메일 인증 구현
  build.gradle
  src/docs/asciidoc/email-auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/niceteam/common/Domain.java
  src/main/java/com/dnd/niceteam/domain/emailauth/EmailAuthRepository.java
  src/main/java/com/dnd/niceteam/domain/emailauth/EmailAuthRepositoryCustom.java
  src/main/java/com/dnd/niceteam/domain/emailauth/EmailAuthRepositoryCustomImpl.java
  src/main/java/com/dnd/niceteam/domain/emailauth/exception/EmailAuthNotFoundException.java
  src/main/java/com/dnd/niceteam/domain/university/UniversityRepository.java
  src/main/java/com/dnd/niceteam/domain/university/exception/InvalidEmailDomainException.java
  src/main/java/com/dnd/niceteam/domain/university/exception/UniversityNotFoundException.java
  src/main/java/com/dnd/niceteam/emailauth/config/EmailConfig.java
  src/main/java/com/dnd/niceteam/emailauth/controller/EmailAuthController.java
  src/main/java/com/dnd/niceteam/emailauth/dto/EmailAuthKeyCheckRequestDto.java
  src/main/java/com/dnd/niceteam/emailauth/dto/EmailAuthKeyCheckResponseDto.java
  src/main/java/com/dnd/niceteam/emailauth/dto/EmailAuthKeySendRequestDto.java
  src/main/java/com/dnd/niceteam/emailauth/service/EmailAuthKeyCreator.java
  src/main/java/com/dnd/niceteam/emailauth/service/EmailAuthService.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/security/SecurityConfig.java
  src/main/resources/application-mail.yml
  src/main/resources/application.yml
  src/test/java/com/dnd/niceteam/domain/emailauth/EmailAuthRepositoryTest.java
  src/test/java/com/dnd/niceteam/emailauth/controller/EmailAuthControllerTest.java
  src/test/java/com/dnd/niceteam/emailauth/service/EmailAuthServiceTest.java
  src/test/resources/application.yml
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
Labels: Type: Feature, Priority: Medium, Status: Available

#24 Feature/#20 프로젝트 Aggregate Entity 추가
  src/main/java/com/dnd/niceteam/domain/project/Project.java
  src/main/java/com/dnd/niceteam/domain/project/ProjectMember.java
  src/main/java/com/dnd/niceteam/domain/project/ProjectStatus.java
  src/main/java/com/dnd/niceteam/domain/project/ProjectType.java
Labels: Status: Review Needed, Priority: Medium

#21 feature/#19 회원가입
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member.adoc
  src/docs/asciidoc/university.adoc
  src/main/java/com/dnd/niceteam/common/Domain.java
  src/main/java/com/dnd/niceteam/domain/account/Account.java
  src/main/java/com/dnd/niceteam/domain/account/AccountRepository.java
  src/main/java/com/dnd/niceteam/domain/code/Field.java
  src/main/java/com/dnd/niceteam/domain/code/Personality.java
  src/main/java/com/dnd/niceteam/domain/common/BaseTimeEntity.java
  src/main/java/com/dnd/niceteam/domain/department/DepartmentRepository.java
  src/main/java/com/dnd/niceteam/domain/department/exception/DepartmentNotFoundException.java
  src/main/java/com/dnd/niceteam/domain/emailauth/EmailAuth.java
  src/main/java/com/dnd/niceteam/domain/emailauth/exception/NotAuthenticatedEmail.java
  src/main/java/com/dnd/niceteam/domain/member/Member.java
  src/main/java/com/dnd/niceteam/domain/member/MemberEditor.java
  src/main/java/com/dnd/niceteam/domain/member/MemberInterest.java
  src/main/java/com/dnd/niceteam/domain/member/MemberRepository.java
  src/main/java/com/dnd/niceteam/domain/member/MemberRepositoryCustom.java
  src/main/java/com/dnd/niceteam/domain/member/MemberRepositoryCustomImpl.java
  src/main/java/com/dnd/niceteam/domain/member/exception/DuplicateEmailException.java
  src/main/java/com/dnd/niceteam/domain/member/exception/DuplicateNicknameException.java
  src/main/java/com/dnd/niceteam/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/dnd/niceteam/domain/memberscore/MemberScore.java
  src/main/java/com/dnd/niceteam/domain/university/UniversityRepository.java
  src/main/java/com/dnd/niceteam/emailauth/dto/EmailAuthKeySendRequestDto.java
  src/main/java/com/dnd/niceteam/emailauth/service/EmailAuthService.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/member/controller/MemberController.java
  src/main/java/com/dnd/niceteam/member/dto/DupCheck.java
  src/main/java/com/dnd/niceteam/member/dto/MemberCreation.java
  src/main/java/com/dnd/niceteam/member/dto/MemberRequestDto.java
  src/main/java/com/dnd/niceteam/member/dto/MemberResponseDto.java
  src/main/java/com/dnd/niceteam/member/service/MemberService.java
  src/main/java/com/dnd/niceteam/security/SecurityConfig.java
  src/main/java/com/dnd/niceteam/university/controller/UniversityController.java
  src/main/java/com/dnd/niceteam/university/dto/DepartmentDto.java
  src/main/java/com/dnd/niceteam/university/dto/UniversityDto.java
  src/main/java/com/dnd/niceteam/university/service/UniversityService.java
  src/test/java/com/dnd/niceteam/domain/member/MemberRepositoryTest.java
  src/test/java/com/dnd/niceteam/emailauth/controller/EmailAuthControllerTest.java
  src/test/java/com/dnd/niceteam/emailauth/service/EmailAuthServiceTest.java
  src/test/java/com/dnd/niceteam/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/niceteam/member/service/MemberServiceTest.java
  src/test/java/com/dnd/niceteam/university/controller/UniversityControllerTest.java
  src/test/java/com/dnd/niceteam/university/service/UniversityServiceTest.java
Labels: Priority: Medium, Status: Available

#26 Feature/#23 팀원 평가 Aggregate Entity 추가
  src/main/java/com/dnd/niceteam/domain/memberreview/MemberReview.java
  src/main/java/com/dnd/niceteam/domain/memberreview/MemberReviewTag.java
  src/main/java/com/dnd/niceteam/domain/memberreview/MemberReviewTagName.java
Labels: Priority: Low, Status: Review Needed

#27 Feature/#25 모집글 Aggregate Entity 추가
  src/main/java/com/dnd/niceteam/domain/applicant/Applicant.java
  src/main/java/com/dnd/niceteam/domain/applicant/ApplicantRepository.java
  src/main/java/com/dnd/niceteam/domain/bookmark/Bookmark.java
  src/main/java/com/dnd/niceteam/domain/bookmark/BookmarkRepository.java
  src/main/java/com/dnd/niceteam/domain/code/ActivityArea.java
  src/main/java/com/dnd/niceteam/domain/code/ProgressStatus.java
  src/main/java/com/dnd/niceteam/domain/code/Type.java
  src/main/java/com/dnd/niceteam/domain/comment/Comment.java
  src/main/java/com/dnd/niceteam/domain/comment/CommentRepository.java
  src/main/java/com/dnd/niceteam/domain/recruiting/ActivityDayTime.java
  src/main/java/com/dnd/niceteam/domain/recruiting/LectureRecruiting.java
  src/main/java/com/dnd/niceteam/domain/recruiting/LectureRecruitingRepository.java
  src/main/java/com/dnd/niceteam/domain/recruiting/LectureTime.java
  src/main/java/com/dnd/niceteam/domain/recruiting/Recruiting.java
  src/main/java/com/dnd/niceteam/domain/recruiting/RecruitingRepository.java
  src/main/java/com/dnd/niceteam/domain/recruiting/SideRecruiting.java
  src/main/java/com/dnd/niceteam/domain/recruiting/SideRecruitingRepository.java
Labels: Type: Feature, Status: Review Needed, Priority: High

#32 Feature/#29 신규 프로젝트 등록 Service 메서드 추가
  src/main/java/com/dnd/niceteam/common/Domain.java
  src/main/java/com/dnd/niceteam/domain/project/ProjectRepository.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectRequest.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectResponse.java
  src/main/java/com/dnd/niceteam/project/exception/InvalidProjectSchedule.java
  src/main/java/com/dnd/niceteam/project/service/ProjectService.java
  src/test/java/com/dnd/niceteam/project/ProjectTestFactory.java
  src/test/java/com/dnd/niceteam/project/service/ProjectServiceTest.java
Labels: Type: Feature, Status: Review Needed, Priority: High

#37 fix(Domain): @Builder & @Column 관련 JPA 테이블 생성 버그 수정
  src/main/java/com/dnd/niceteam/domain/applicant/Applicant.java
  src/main/java/com/dnd/niceteam/domain/comment/Comment.java
  src/main/java/com/dnd/niceteam/domain/recruiting/LectureRecruiting.java
  src/main/java/com/dnd/niceteam/domain/recruiting/Recruiting.java
Labels: Type: Bug, Status: Review Needed, Priority: Critical

#45 Feature/#22 투표 Aggregate Entity 추가
  src/main/java/com/dnd/niceteam/domain/vote/Vote.java
  src/main/java/com/dnd/niceteam/domain/vote/VoteGroup.java
  src/main/java/com/dnd/niceteam/domain/vote/VoteGroupToCompleteProject.java
  src/main/java/com/dnd/niceteam/domain/vote/VoteGroupToExpel.java
  src/main/java/com/dnd/niceteam/domain/vote/VoteType.java
Labels: Type: Feature, Priority: Medium

#46 Refactor/#43 프로젝트, 팀원, 팀원 후기 필드 속성 및 속성명 리팩토링
  src/main/java/com/dnd/niceteam/domain/project/Project.java
  src/main/java/com/dnd/niceteam/domain/project/ProjectMember.java
  src/main/java/com/dnd/niceteam/domain/review/MemberReview.java
  src/main/java/com/dnd/niceteam/domain/review/MemberReviewTag.java
  src/main/java/com/dnd/niceteam/domain/review/MemberReviewTagName.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectRequest.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectResponse.java
  src/main/java/com/dnd/niceteam/project/service/ProjectService.java
  src/test/java/com/dnd/niceteam/project/ProjectTestFactory.java
  src/test/java/com/dnd/niceteam/project/service/ProjectServiceTest.java
Labels: Type: Refactor, Priority: Medium

#50 Refactor/#49 모집글 자식 Entity를 프로젝트로 이동
  src/main/java/com/dnd/niceteam/domain/project/LectureProject.java
  src/main/java/com/dnd/niceteam/domain/project/LectureProjectRepository.java
  src/main/java/com/dnd/niceteam/domain/project/LectureTime.java
  src/main/java/com/dnd/niceteam/domain/project/Project.java
  src/main/java/com/dnd/niceteam/domain/project/ProjectType.java
  src/main/java/com/dnd/niceteam/domain/project/SideProject.java
  src/main/java/com/dnd/niceteam/domain/recruiting/LectureRecruiting.java
  src/main/java/com/dnd/niceteam/domain/recruiting/LectureRecruitingRepository.java
  src/main/java/com/dnd/niceteam/domain/recruiting/Recruiting.java
  src/main/java/com/dnd/niceteam/domain/recruiting/RecruitingRepository.java
  src/main/java/com/dnd/niceteam/domain/recruiting/SideRecruitingRepository.java
  src/main/java/com/dnd/niceteam/project/dto/DepartmentResponse.java
  src/main/java/com/dnd/niceteam/project/dto/LectureProjectRequest.java
  src/main/java/com/dnd/niceteam/project/dto/LectureProjectResponse.java
  src/main/java/com/dnd/niceteam/project/dto/LectureTimeRequest.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectRequest.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectResponse.java
  src/main/java/com/dnd/niceteam/project/dto/SideProjectRequest.java
  src/main/java/com/dnd/niceteam/project/dto/UniversityResponse.java
  src/main/java/com/dnd/niceteam/project/service/LectureProjectService.java
  src/main/java/com/dnd/niceteam/project/service/ProjectService.java
  src/main/java/com/dnd/niceteam/review/service/MemberReviewService.java
  src/main/java/com/dnd/niceteam/security/UserDetailsServiceImpl.java
  src/test/java/com/dnd/niceteam/project/LectureProjectTestFactory.java
  src/test/java/com/dnd/niceteam/project/ProjectTestFactory.java
  src/test/java/com/dnd/niceteam/project/service/LectureProjectServiceTest.java
  src/test/java/com/dnd/niceteam/project/service/ProjectServiceTest.java
  src/test/java/com/dnd/niceteam/review/service/MemberReviewServiceTest.java
Labels: Status: Review Needed, Priority: Critical, Type: Refactor

#54 bugfix/#53 day 약어 칼럼명 수정 및 ProjectRepository 대체
  src/main/java/com/dnd/niceteam/domain/project/LectureTime.java
  src/main/java/com/dnd/niceteam/domain/project/Project.java
  src/main/java/com/dnd/niceteam/domain/recruiting/ActivityDayTime.java
  src/test/java/com/dnd/niceteam/domain/project/ProjectMemberRepositoryTest.java
Labels: Type: Bug, Priority: Critical, Status: Available

#61 bugfix: 7기 2조의 수준은 어디까지?! 페이지네이션의 오류를 찾아라!
  src/main/java/com/dnd/niceteam/common/dto/Pagination.java
  src/test/java/com/dnd/niceteam/common/dto/PaginationTest.java
Labels: Type: Bug, Status: Review Needed, Priority: Critical

#62 Feature/#55 팀원 후기 건너뛰기 기능 추가
  .gitignore
  build.gradle
  src/docs/asciidoc/member-review.adoc
  src/main/java/com/dnd/niceteam/domain/project/Project.java
  src/main/java/com/dnd/niceteam/domain/project/ProjectRepository.java
  src/main/java/com/dnd/niceteam/domain/review/MemberReview.java
  src/main/java/com/dnd/niceteam/member/util/MemberUtils.java
  src/main/java/com/dnd/niceteam/project/service/LectureProjectService.java
  src/main/java/com/dnd/niceteam/review/controller/MemberReviewController.java
  src/main/java/com/dnd/niceteam/review/dto/MemberReviewRequest.java
  src/main/java/com/dnd/niceteam/review/service/MemberReviewService.java
  src/main/java/com/dnd/niceteam/security/CurrentUser.java
  src/main/resources/application-db.yml
  src/test/java/com/dnd/niceteam/domain/project/ProjectMemberRepositoryTest.java
  src/test/java/com/dnd/niceteam/project/service/LectureProjectServiceTest.java
  src/test/java/com/dnd/niceteam/review/MemberReviewTestFactory.java
  src/test/java/com/dnd/niceteam/review/controller/MemberReviewControllerTest.java
  src/test/java/com/dnd/niceteam/review/service/MemberReviewServiceTest.java
Labels: Type: Feature, Status: Review Needed, Priority: Medium

#71 fix(MemberReview): 팀원 후기 태그 Cascade.Persist 버그 수정
  src/main/java/com/dnd/niceteam/domain/review/MemberReview.java
  src/main/java/com/dnd/niceteam/domain/review/MemberReviewTag.java
  src/main/java/com/dnd/niceteam/review/dto/MemberReviewRequest.java
  src/main/java/com/dnd/niceteam/review/service/MemberReviewService.java
Labels: Type: Feature, Priority: Medium, Status: Available

#72 Feature/#66 사이드 팀플 추가 & 모집글, 프로젝트 모듈 간 End Point 정리
  src/main/java/com/dnd/niceteam/domain/project/LectureProjectRepository.java
  src/main/java/com/dnd/niceteam/domain/project/SideProjectRepository.java
  src/main/java/com/dnd/niceteam/project/dto/LectureProjectRequest.java
  src/main/java/com/dnd/niceteam/project/dto/LectureProjectResponse.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectRequest.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectResponse.java
  src/main/java/com/dnd/niceteam/project/dto/SideProjectRequest.java
  src/main/java/com/dnd/niceteam/project/service/LectureProjectService.java
  src/main/java/com/dnd/niceteam/project/service/ProjectService.java
  src/main/java/com/dnd/niceteam/review/service/MemberReviewService.java
  src/test/java/com/dnd/niceteam/domain/project/ProjectMemberRepositoryTest.java
  src/test/java/com/dnd/niceteam/project/ProjectTestFactory.java
  src/test/java/com/dnd/niceteam/project/service/LectureProjectServiceTest.java
  src/test/java/com/dnd/niceteam/project/service/ProjectServiceTest.java
  src/test/java/com/dnd/niceteam/review/MemberReviewTestFactory.java
  src/test/java/com/dnd/niceteam/review/controller/MemberReviewControllerTest.java
  src/test/java/com/dnd/niceteam/review/service/MemberReviewServiceTest.java
Labels: Type: Feature, Status: Review Needed, Priority: Critical

#64 Feature/#59 지원자 등록 기능
  src/docs/asciidoc/applicant.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/niceteam/applicant/controller/ApplicantController.java
  src/main/java/com/dnd/niceteam/applicant/dto/ApplicantCreation.java
  src/main/java/com/dnd/niceteam/applicant/service/ApplicantService.java
  src/main/java/com/dnd/niceteam/comment/dto/CommentDetail.java
  src/main/java/com/dnd/niceteam/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/dnd/niceteam/domain/recruiting/Applicant.java
  src/main/java/com/dnd/niceteam/domain/recruiting/ApplicantRepository.java
  src/main/java/com/dnd/niceteam/domain/recruiting/exception/ApplyAlreadyAcceptedException.java
  src/main/java/com/dnd/niceteam/domain/recruiting/exception/ApplyCancelImpossibleRecruitingException.java
  src/main/java/com/dnd/niceteam/domain/recruiting/exception/ApplyImpossibleRecruitingException.java
  src/main/java/com/dnd/niceteam/domain/recruiting/exception/InvalidRecruitingTypeException.java
  src/main/java/com/dnd/niceteam/domain/recruiting/exception/RecruitingNotFoundException.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/recruiting/exception/InvalidRecruitingType.java
  src/main/java/com/dnd/niceteam/recruiting/service/RecruitingServiceStrategy.java
  src/test/java/com/dnd/niceteam/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/dnd/niceteam/applicant/service/ApplicantServiceTest.java
  src/test/java/com/dnd/niceteam/comment/CommentTestFactory.java
Labels: Type: Bug, Type: Feature, Status: Review Needed, Priority: Medium

#74 Feature/#73 프로젝트 수정 기능 추가
  src/main/java/com/dnd/niceteam/domain/project/LectureProject.java
  src/main/java/com/dnd/niceteam/domain/project/Project.java
  src/main/java/com/dnd/niceteam/domain/project/ProjectRepository.java
  src/main/java/com/dnd/niceteam/domain/project/SideProject.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectRequest.java
  src/main/java/com/dnd/niceteam/project/service/ProjectService.java
  src/main/java/com/dnd/niceteam/review/service/MemberReviewService.java
  src/test/java/com/dnd/niceteam/project/ProjectTestFactory.java
  src/test/java/com/dnd/niceteam/project/service/ProjectServiceTest.java
  src/test/java/com/dnd/niceteam/review/service/MemberReviewServiceTest.java
Labels: Type: Feature, Status: Review Needed, Priority: High

#77 feature/#69 북마크 생성
  src/docs/asciidoc/bookmark.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/niceteam/bookmark/controller/BookmarkController.java
  src/main/java/com/dnd/niceteam/bookmark/dto/BookmarkCreation.java
  src/main/java/com/dnd/niceteam/bookmark/service/BookmarkService.java
  src/main/java/com/dnd/niceteam/common/Domain.java
  src/main/java/com/dnd/niceteam/domain/bookmark/Bookmark.java
  src/main/java/com/dnd/niceteam/domain/bookmark/BookmarkRepository.java
  src/main/java/com/dnd/niceteam/domain/bookmark/exception/BookmarkExistingException.java
  src/main/java/com/dnd/niceteam/domain/recruiting/Recruiting.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/test/java/com/dnd/niceteam/bookmark/controller/BookmarkControllerTest.java
  src/test/java/com/dnd/niceteam/bookmark/service/BookmarkServiceTest.java
Labels: Type: Feature, Priority: Medium, Status: Available

#79 Feature/#75 내 팀플 목록 조회 기능 추가
  src/docs/asciidoc/project.adoc
  src/main/java/com/dnd/niceteam/common/dto/Pagination.java
  src/main/java/com/dnd/niceteam/domain/project/Project.java
  src/main/java/com/dnd/niceteam/domain/project/ProjectRepository.java
  src/main/java/com/dnd/niceteam/domain/project/ProjectSpecification.java
  src/main/java/com/dnd/niceteam/project/controller/ProjectController.java
  src/main/java/com/dnd/niceteam/project/dto/LectureTimeResponse.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectResponse.java
  src/main/java/com/dnd/niceteam/project/service/ProjectService.java
  src/test/java/com/dnd/niceteam/project/controller/ProjectControllerTest.java
Labels: Type: Feature, Status: Review Needed, Priority: Medium

#81 Feature/#42 모집글 등록 기능
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/recruiting.adoc
  src/main/java/com/dnd/niceteam/domain/project/Project.java
  src/main/java/com/dnd/niceteam/domain/recruiting/Recruiting.java
  src/main/java/com/dnd/niceteam/recruiting/controller/RecruitingController.java
  src/main/java/com/dnd/niceteam/recruiting/service/RecruitingService.java
  src/test/java/com/dnd/niceteam/applicant/service/ApplicantServiceTest.java
  src/test/java/com/dnd/niceteam/comment/CommentTestFactory.java
  src/test/java/com/dnd/niceteam/comment/DtoFactoryForTest.java
  src/test/java/com/dnd/niceteam/comment/EntityFactoryForTest.java
  src/test/java/com/dnd/niceteam/recruiting/controller/RecruitingControllerTest.java
Labels: Type: Documentation, Type: Feature, Status: Review Needed, Priority: High

#82 feature/#78 북마크 제거 및 CurrentUsernameArgumentResolver
  src/docs/asciidoc/bookmark.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/niceteam/bookmark/controller/BookmarkController.java
  src/main/java/com/dnd/niceteam/bookmark/dto/BookmarkDeletion.java
  src/main/java/com/dnd/niceteam/bookmark/service/BookmarkService.java
  src/main/java/com/dnd/niceteam/common/config/WebConfig.java
  src/main/java/com/dnd/niceteam/domain/bookmark/BookmarkRepository.java
  src/main/java/com/dnd/niceteam/domain/bookmark/BookmarkRepositoryCustom.java
  src/main/java/com/dnd/niceteam/domain/bookmark/BookmarkRepositoryCustomImpl.java
  src/main/java/com/dnd/niceteam/domain/bookmark/exception/BookmarkExistingException.java
  src/main/java/com/dnd/niceteam/domain/bookmark/exception/BookmarkNotFoundException.java
  src/main/java/com/dnd/niceteam/domain/bookmark/exception/BookmarkNotOwnedException.java
  src/main/java/com/dnd/niceteam/domain/recruiting/Recruiting.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/security/CurrentUsername.java
  src/main/java/com/dnd/niceteam/security/arguementresolver/CurrentUsernameArgumentResolver.java
  src/test/java/com/dnd/niceteam/bookmark/controller/BookmarkControllerTest.java
  src/test/java/com/dnd/niceteam/bookmark/service/BookmarkServiceTest.java
Labels: Type: Feature, Priority: Medium, Status: Available

#86 Feature/#84 모집글 조회 (상세 조회, 내가쓴글 목록 조회, 사이드 모집글 추천 조회)
  src/docs/asciidoc/recruiting.adoc
  src/main/java/com/dnd/niceteam/common/Domain.java
  src/main/java/com/dnd/niceteam/domain/recruiting/Recruiting.java
  src/main/java/com/dnd/niceteam/domain/recruiting/RecruitingRepository.java
  src/main/java/com/dnd/niceteam/domain/recruiting/RecruitingRepositoryCustom.java
  src/main/java/com/dnd/niceteam/domain/recruiting/RecruitingRepositoryCustomImpl.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/recruiting/controller/RecruitingController.java
  src/main/java/com/dnd/niceteam/recruiting/dto/RecruitingCreation.java
  src/main/java/com/dnd/niceteam/recruiting/dto/RecruitingFind.java
  src/main/java/com/dnd/niceteam/recruiting/service/RecruitingService.java
  src/test/java/com/dnd/niceteam/applicant/service/ApplicantServiceTest.java
  src/test/java/com/dnd/niceteam/comment/DtoFactoryForTest.java
  src/test/java/com/dnd/niceteam/comment/EntityFactoryForTest.java
  src/test/java/com/dnd/niceteam/domain/project/LectureProjectRepositoryTest.java
  src/test/java/com/dnd/niceteam/domain/recruiting/RecruitingRepositoryTest.java
  src/test/java/com/dnd/niceteam/recruiting/controller/RecruitingControllerTest.java
  src/test/java/com/dnd/niceteam/recruiting/service/RecruitingServiceTest.java
Labels: Type: Bug, Type: Feature, Type: Question, Priority: High, Status: Available

#89 Feature/#88 Recruiting 모집글 Set<Personality> 필드 1개를 Set<Enum>타입의 2개로 분리
  src/main/java/com/dnd/niceteam/domain/recruiting/Recruiting.java
  src/main/java/com/dnd/niceteam/recruiting/dto/RecruitingCreation.java
  src/main/java/com/dnd/niceteam/recruiting/dto/RecruitingFind.java
  src/test/java/com/dnd/niceteam/comment/DtoFactoryForTest.java
  src/test/java/com/dnd/niceteam/comment/EntityFactoryForTest.java
  src/test/java/com/dnd/niceteam/recruiting/controller/RecruitingControllerTest.java
  src/test/java/com/dnd/niceteam/recruiting/service/RecruitingServiceTest.java
Labels: Type: Feature, Status: Review Needed, Priority: Medium

#85 Feature/#34 내 팀플 상세 조회 기능 추가
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/project.adoc
  src/main/java/com/dnd/niceteam/domain/project/ProjectRepository.java
  src/main/java/com/dnd/niceteam/domain/project/ProjectSpecification.java
  src/main/java/com/dnd/niceteam/project/controller/ProjectController.java
  src/main/java/com/dnd/niceteam/project/dto/PersonalityResponse.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectMemberResponse.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectResponse.java
  src/main/java/com/dnd/niceteam/project/service/ProjectService.java
  src/test/java/com/dnd/niceteam/project/controller/ProjectControllerTest.java
Labels: Type: Feature, Status: Review Needed, Priority: Medium

#90 feature/#83 북마크 페이지 조회
  src/docs/asciidoc/bookmark.adoc
  src/main/java/com/dnd/niceteam/bookmark/controller/BookmarkController.java
  src/main/java/com/dnd/niceteam/bookmark/dto/BookmarkDto.java
  src/main/java/com/dnd/niceteam/bookmark/service/BookmarkService.java
  src/main/java/com/dnd/niceteam/common/util/PaginationUtil.java
  src/main/java/com/dnd/niceteam/domain/bookmark/BookmarkRepository.java
  src/test/java/com/dnd/niceteam/bookmark/controller/BookmarkControllerTest.java
  src/test/java/com/dnd/niceteam/bookmark/service/BookmarkServiceTest.java
  src/test/java/com/dnd/niceteam/common/util/PaginationUtilTest.java
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-parameters.snippet
Labels: Type: Feature, Priority: Medium, Status: Available

#91 Feature/#87 모집글 지원 등록 취소 기능
  src/docs/asciidoc/applicant.adoc
  src/main/java/com/dnd/niceteam/applicant/controller/ApplicantController.java
  src/main/java/com/dnd/niceteam/applicant/dto/ApplicantCreation.java
  src/main/java/com/dnd/niceteam/applicant/service/ApplicantService.java
  src/main/java/com/dnd/niceteam/domain/recruiting/ApplicantRepository.java
  src/main/java/com/dnd/niceteam/domain/recruiting/ApplicantRepositoryCustom.java
  src/main/java/com/dnd/niceteam/domain/recruiting/ApplicantRepositoryCustomImpl.java
  src/main/java/com/dnd/niceteam/domain/recruiting/exception/ApplicantNotFoundException.java
  src/main/java/com/dnd/niceteam/domain/recruiting/exception/ApplyCancelImpossibleRecruitingException.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/test/java/com/dnd/niceteam/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/dnd/niceteam/applicant/service/ApplicantServiceTest.java
Labels: Type: Documentation, Priority: Low, Type: Feature, Status: Review Needed

#93 Feature/#80 팀원 내보내기 투표 기능 추가
  src/docs/asciidoc/vote.adoc
  src/main/java/com/dnd/niceteam/common/Domain.java
  src/main/java/com/dnd/niceteam/domain/code/VoteType.java
  src/main/java/com/dnd/niceteam/domain/vote/Vote.java
  src/main/java/com/dnd/niceteam/domain/vote/VoteGroup.java
  src/main/java/com/dnd/niceteam/domain/vote/VoteGroupToCompleteProject.java
  src/main/java/com/dnd/niceteam/domain/vote/VoteGroupToExpel.java
  src/main/java/com/dnd/niceteam/domain/vote/VoteGroupToExpelRepository.java
  src/main/java/com/dnd/niceteam/domain/vote/VoteRepository.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/vote/controller/VoteController.java
  src/main/java/com/dnd/niceteam/vote/dto/VoteRequest.java
  src/main/java/com/dnd/niceteam/vote/exception/AlreadyVotedException.java
  src/main/java/com/dnd/niceteam/vote/exception/ExpiredVoteGroupException.java
  src/main/java/com/dnd/niceteam/vote/exception/NotEnoughProjectMembersException.java
  src/main/java/com/dnd/niceteam/vote/exception/SelfVoteException.java
  src/main/java/com/dnd/niceteam/vote/service/VoteService.java
  src/test/java/com/dnd/niceteam/vote/controller/VoteControllerTest.java
Labels: Type: Feature, Priority: Medium, Status: Available

#98 refactor/#92 AactivityDayTime 활동 일정: collection value type으로 수정 및 북마크 여부 필드 추가
  src/main/java/com/dnd/niceteam/domain/recruiting/ActivityDayTime.java
  src/main/java/com/dnd/niceteam/domain/recruiting/Recruiting.java
  src/main/java/com/dnd/niceteam/domain/recruiting/RecruitingRepository.java
  src/main/java/com/dnd/niceteam/domain/recruiting/RecruitingRepositoryCustom.java
  src/main/java/com/dnd/niceteam/domain/recruiting/RecruitingRepositoryCustomImpl.java
  src/main/java/com/dnd/niceteam/recruiting/controller/RecruitingController.java
  src/main/java/com/dnd/niceteam/recruiting/dto/ActivityDayTimeDto.java
  src/main/java/com/dnd/niceteam/recruiting/dto/RecruitingCreation.java
  src/main/java/com/dnd/niceteam/recruiting/dto/RecruitingFind.java
  src/main/java/com/dnd/niceteam/recruiting/service/RecruitingService.java
  src/test/java/com/dnd/niceteam/comment/DtoFactoryForTest.java
  src/test/java/com/dnd/niceteam/comment/EntityFactoryForTest.java
  src/test/java/com/dnd/niceteam/domain/recruiting/RecruitingRepositoryTest.java
  src/test/java/com/dnd/niceteam/recruiting/controller/RecruitingControllerTest.java
  src/test/java/com/dnd/niceteam/recruiting/service/RecruitingServiceTest.java
Labels: Priority: Low, Type: Feature, Status: Review Needed, Status: Available

#96 Feature/#94 팀플 완료 투표 기능 추가
  src/main/java/com/dnd/niceteam/domain/vote/VoteGroupToCompleteProject.java
  src/main/java/com/dnd/niceteam/domain/vote/VoteGroupToCompleteProjectRepository.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/project/exception/ProjectAlreadyDoneException.java
  src/main/java/com/dnd/niceteam/project/exception/ProjectMemberNotFoundException.java
  src/main/java/com/dnd/niceteam/project/exception/ProjectNotFoundException.java
  src/main/java/com/dnd/niceteam/project/service/ProjectService.java
  src/main/java/com/dnd/niceteam/review/service/MemberReviewService.java
  src/main/java/com/dnd/niceteam/vote/service/VoteService.java
  src/test/java/com/dnd/niceteam/recruiting/service/RecruitingServiceTest.java
  src/test/java/com/dnd/niceteam/vote/VoteTestFactory.java
  src/test/java/com/dnd/niceteam/vote/controller/VoteControllerTest.java
  src/test/java/com/dnd/niceteam/vote/service/VoteServiceTest.java
Labels: Type: Feature, Status: Review Needed, Priority: Medium

#97 Feature/#95 프로젝트 팀원 수락 기능 추가
  src/main/java/com/dnd/niceteam/domain/member/Member.java
  src/main/java/com/dnd/niceteam/domain/project/Project.java
  src/main/java/com/dnd/niceteam/domain/project/ProjectMember.java
  src/main/java/com/dnd/niceteam/domain/recruiting/Applicant.java
  src/main/java/com/dnd/niceteam/domain/recruiting/Recruiting.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/project/controller/ProjectController.java
  src/main/java/com/dnd/niceteam/project/dto/ProjectMemberRequest.java
  src/main/java/com/dnd/niceteam/project/exception/ProjectMemberAlreadyJoinedException.java
  src/main/java/com/dnd/niceteam/project/service/ProjectService.java
  src/main/java/com/dnd/niceteam/recruiting/exception/OnlyRecruiterAvailableException.java
  src/main/java/com/dnd/niceteam/recruiting/service/RecruitingService.java
  src/test/java/com/dnd/niceteam/comment/controller/CommentControllerTest.java
  src/test/java/com/dnd/niceteam/project/ProjectTestFactory.java
  src/test/java/com/dnd/niceteam/project/controller/ProjectControllerTest.java
  src/test/java/com/dnd/niceteam/project/service/ProjectServiceTest.java
Labels: Type: Feature, Status: Review Needed, Priority: Medium

#100 Feature/#13 푸쉬 알림 기능 추가 + 테스트 코드 픽스
  .gitignore
  build.gradle
  src/main/java/com/dnd/niceteam/NiceteamBackendApplication.java
  src/main/java/com/dnd/niceteam/common/Domain.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/notification/config/FirebaseConfig.java
  src/main/java/com/dnd/niceteam/notification/config/FirebaseProperties.java
  src/main/java/com/dnd/niceteam/notification/config/NotificationParams.java
  src/main/java/com/dnd/niceteam/notification/controller/NotificationController.java
  src/main/java/com/dnd/niceteam/notification/dto/NotificationRequestDto.java
  src/main/java/com/dnd/niceteam/notification/dto/NotificationResponseDto.java
  src/main/java/com/dnd/niceteam/notification/exception/NotificationPushFailedException.java
  src/main/java/com/dnd/niceteam/notification/service/FirebaseCloudMessagingService.java
  src/main/java/com/dnd/niceteam/notification/service/NotificationService.java
  src/main/java/com/dnd/niceteam/notification/util/FCMUtil.java
  src/main/resources/application-firebase.yml
  src/main/resources/application.yml
  src/test/java/com/dnd/niceteam/notification/service/NotificationServiceTest.java
  src/test/java/com/dnd/niceteam/project/service/ProjectServiceTest.java
  src/test/java/com/dnd/niceteam/vote/VoteTestFactory.java
Labels: Type: Feature, Status: Review Needed, Priority: Medium

#108 fix(Project): 프로젝트 생성 시 DTYPE (type) 컬럼 값 null 문제 해결
  src/main/java/com/dnd/niceteam/domain/project/Project.java
Labels: Type: Bug, Priority: High, Status: Available

#103 Feature/#99 Recruiting 모집글 검색 목록 조회
  src/docs/asciidoc/recruiting.adoc
  src/main/java/com/dnd/niceteam/domain/recruiting/Recruiting.java
  src/main/java/com/dnd/niceteam/domain/recruiting/RecruitingRepositoryCustom.java
  src/main/java/com/dnd/niceteam/domain/recruiting/RecruitingRepositoryCustomImpl.java
  src/main/java/com/dnd/niceteam/recruiting/controller/RecruitingController.java
  src/main/java/com/dnd/niceteam/recruiting/dto/RecruitingCreation.java
  src/main/java/com/dnd/niceteam/recruiting/dto/RecruitingFind.java
  src/main/java/com/dnd/niceteam/recruiting/service/RecruitingService.java
  src/test/java/com/dnd/niceteam/comment/DtoFactoryForTest.java
  src/test/java/com/dnd/niceteam/domain/recruiting/RecruitingRepositoryTest.java
  src/test/java/com/dnd/niceteam/recruiting/controller/RecruitingControllerTest.java
  src/test/java/com/dnd/niceteam/recruiting/service/RecruitingServiceTest.java
Labels: Type: Feature, Status: Review Needed, Priority: High

#106 feature/#68 리뷰 등록에 회원점수 적용
  src/main/java/com/dnd/niceteam/domain/code/ReviewTag.java
  src/main/java/com/dnd/niceteam/domain/memberscore/MemberScore.java
  src/main/java/com/dnd/niceteam/domain/memberscore/MemberScoreRepository.java
  src/main/java/com/dnd/niceteam/domain/memberscore/MemberScoreRepositoryCustom.java
  src/main/java/com/dnd/niceteam/domain/memberscore/MemberScoreRepositoryCustomImpl.java
  src/main/java/com/dnd/niceteam/domain/memberscore/exception/MemberScoreNotFoundException.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/member/service/MemberService.java
  src/main/java/com/dnd/niceteam/review/service/MemberReviewService.java
  src/test/java/com/dnd/niceteam/domain/memberscore/MemberScoreRepositoryTest.java
  src/test/java/com/dnd/niceteam/domain/memberscore/MemberScoreTest.java
  src/test/java/com/dnd/niceteam/review/MemberReviewTestFactory.java
  src/test/java/com/dnd/niceteam/review/service/MemberReviewServiceTest.java
Labels: Type: Feature, Priority: Medium, Status: Available

#115 Feature/#112 Comment 댓글 목록 조회(2 cases), 제거 및 수정
  src/docs/asciidoc/comment.adoc
  src/main/generated/com/dnd/niceteam/domain/account/QAccount.java
  src/main/generated/com/dnd/niceteam/domain/bookmark/QBookmark.java
  src/main/generated/com/dnd/niceteam/domain/code/QPersonality.java
  src/main/generated/com/dnd/niceteam/domain/comment/QComment.java
  src/main/generated/com/dnd/niceteam/domain/common/QBaseEntity.java
  src/main/generated/com/dnd/niceteam/domain/common/QBaseTimeEntity.java
  src/main/generated/com/dnd/niceteam/domain/department/QDepartment.java
  src/main/generated/com/dnd/niceteam/domain/emailauth/QEmailAuth.java
  src/main/generated/com/dnd/niceteam/domain/member/QMember.java
  src/main/generated/com/dnd/niceteam/domain/memberscore/QMemberScore.java
  src/main/generated/com/dnd/niceteam/domain/project/QLectureProject.java
  src/main/generated/com/dnd/niceteam/domain/project/QLectureTime.java
  src/main/generated/com/dnd/niceteam/domain/project/QProject.java
  src/main/generated/com/dnd/niceteam/domain/project/QProjectMember.java
  src/main/generated/com/dnd/niceteam/domain/project/QSideProject.java
  src/main/generated/com/dnd/niceteam/domain/recruiting/QActivityDayTime.java
  src/main/generated/com/dnd/niceteam/domain/recruiting/QApplicant.java
  src/main/generated/com/dnd/niceteam/domain/recruiting/QRecruiting.java
  src/main/generated/com/dnd/niceteam/domain/review/QMemberReview.java
  src/main/generated/com/dnd/niceteam/domain/review/QMemberReviewTag.java
  src/main/generated/com/dnd/niceteam/domain/university/QUniversity.java
  src/main/generated/com/dnd/niceteam/domain/vote/QVote.java
  src/main/generated/com/dnd/niceteam/domain/vote/QVoteGroup.java
  src/main/generated/com/dnd/niceteam/domain/vote/QVoteGroupToCompleteProject.java
  src/main/generated/com/dnd/niceteam/domain/vote/QVoteGroupToExpel.java
  src/main/java/com/dnd/niceteam/comment/controller/CommentController.java
  src/main/java/com/dnd/niceteam/comment/dto/CommentCreation.java
  src/main/java/com/dnd/niceteam/comment/dto/CommentDetail.java
  src/main/java/com/dnd/niceteam/comment/dto/CommentFind.java
  src/main/java/com/dnd/niceteam/comment/dto/CommentModify.java
  src/main/java/com/dnd/niceteam/comment/service/CommentService.java
  src/main/java/com/dnd/niceteam/domain/code/ProgressStatus.java
  src/main/java/com/dnd/niceteam/domain/comment/Comment.java
  src/main/java/com/dnd/niceteam/domain/comment/CommentRepository.java
  src/main/java/com/dnd/niceteam/domain/comment/CommentRepositoryCustom.java
  src/main/java/com/dnd/niceteam/domain/comment/CommentRepositoryCustomImpl.java
  src/main/java/com/dnd/niceteam/domain/recruiting/Recruiting.java
  src/main/java/com/dnd/niceteam/domain/recruiting/RecruitingRepository.java
  src/main/java/com/dnd/niceteam/domain/recruiting/RecruitingStatus.java
  src/main/java/com/dnd/niceteam/recruiting/controller/RecruitingController.java
  src/main/java/com/dnd/niceteam/recruiting/dto/RecruitingCreation.java
  src/main/java/com/dnd/niceteam/recruiting/dto/RecruitingFind.java
  src/main/java/com/dnd/niceteam/recruiting/service/RecruitingService.java
  src/test/java/com/dnd/niceteam/comment/DtoFactoryForTest.java
  src/test/java/com/dnd/niceteam/comment/EntityFactoryForTest.java
  src/test/java/com/dnd/niceteam/comment/controller/CommentControllerTest.java
  src/test/java/com/dnd/niceteam/comment/service/CommentServiceTest.java
  src/test/java/com/dnd/niceteam/domain/recruiting/RecruitingRepositoryTest.java
  src/test/java/com/dnd/niceteam/recruiting/controller/RecruitingControllerTest.java
  src/test/java/com/dnd/niceteam/recruiting/service/RecruitingServiceTest.java
Labels: Type: Feature, Priority: Medium

#116 Feature/#114 Applicant 지원 현황 목록 조회
  src/docs/asciidoc/applicant.adoc
  src/main/java/com/dnd/niceteam/applicant/controller/ApplicantController.java
  src/main/java/com/dnd/niceteam/applicant/dto/ApplicantFind.java
  src/main/java/com/dnd/niceteam/applicant/service/ApplicantService.java
  src/main/java/com/dnd/niceteam/domain/recruiting/ApplicantRepository.java
  src/main/java/com/dnd/niceteam/domain/recruiting/ApplicantRepositoryCustom.java
  src/main/java/com/dnd/niceteam/domain/recruiting/ApplicantRepositoryCustomImpl.java
  src/main/java/com/dnd/niceteam/domain/recruiting/exception/InvalidApplicantTypeException.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/test/java/com/dnd/niceteam/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/dnd/niceteam/applicant/service/ApplicantServiceTest.java
  src/test/java/com/dnd/niceteam/domain/recruiting/ApplicantRepositoryTest.java
Labels: Type: Feature, Priority: Medium
