Repository dnd-side-project/dnd-7th-2-backend, pull requests merged in 2022-07, with the labels that each got.

#6 Feature/#3 에러 공통 처리
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_development.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/dnd/niceteam/common/Domain.java
  src/main/java/com/dnd/niceteam/common/dto/ApiResult.java
  src/main/java/com/dnd/niceteam/error/ApiExceptionHandler.java
  src/main/java/com/dnd/niceteam/error/ExceptionAspect.java
  src/main/java/com/dnd/niceteam/error/dto/ErrorResponseDto.java
  src/main/java/com/dnd/niceteam/error/exception/BusinessException.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/resources/application-jwt.yml
Labels: Type: Feature, Status: Review Needed, Priority: High

#8 feature/#7 docs: rest docs 틀 잡기
  src/docs/asciidoc/index.adoc
  src/test/java/com/dnd/niceteam/common/CommonDocsController.java
  src/test/java/com/dnd/niceteam/common/CommonDocsControllerTest.java
  src/test/java/com/dnd/niceteam/common/RestDocsConfig.java
  src/test/java/com/dnd/niceteam/common/TestJpaConfig.java
  src/test/resources/application.yml
  src/test/resources/template/asciidoc/request-fields.snippet
Labels: Type: Documentation, Priority: Low, Status: Available

#4 Feature/#2 authentication
  build.gradle
  src/main/java/com/dnd/niceteam/error/exception/BusinessException.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/error/exception/MemberNotFoundException.java
  src/main/java/com/dnd/niceteam/error/exception/RefreshTokenIsNullException.java
  src/main/java/com/dnd/niceteam/error/exception/TokenInvalidException.java
  src/main/java/com/dnd/niceteam/member/controller/MemberController.java
  src/main/java/com/dnd/niceteam/member/domain/Member.java
  src/main/java/com/dnd/niceteam/member/domain/Role.java
  src/main/java/com/dnd/niceteam/member/dto/MemberRequestDto.java
  src/main/java/com/dnd/niceteam/member/dto/MemberResponseDto.java
  src/main/java/com/dnd/niceteam/member/repository/MemberRepository.java
  src/main/java/com/dnd/niceteam/member/service/MemberService.java
  src/main/java/com/dnd/niceteam/security/SecurityConfig.java
  src/main/java/com/dnd/niceteam/security/UserDetailsImpl.java
  src/main/java/com/dnd/niceteam/security/UserDetailsServiceImpl.java
  src/main/java/com/dnd/niceteam/security/auth/controller/AuthController.java
  src/main/java/com/dnd/niceteam/security/auth/dto/AuthRequestDto.java
  src/main/java/com/dnd/niceteam/security/auth/dto/AuthResponseDto.java
  src/main/java/com/dnd/niceteam/security/auth/service/AuthService.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtTokenProvider.java
Labels: Type: Feature, Status: Review Needed, Priority: High

#9 Feature/#2 authentication 로그인 보완
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/niceteam/common/Domain.java
  src/main/java/com/dnd/niceteam/common/config/JpaConfig.java
  src/main/java/com/dnd/niceteam/common/domain/BaseEntity.java
  src/main/java/com/dnd/niceteam/common/domain/BaseTimeEntity.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/error/exception/MemberNotFoundException.java
  src/main/java/com/dnd/niceteam/error/exception/RefreshTokenIsNullException.java
  src/main/java/com/dnd/niceteam/error/exception/TokenInvalidException.java
  src/main/java/com/dnd/niceteam/member/domain/Member.java
  src/main/java/com/dnd/niceteam/member/exception/MemberNotFoundException.java
  src/main/java/com/dnd/niceteam/security/SecurityConfig.java
  src/main/java/com/dnd/niceteam/security/UserDetailsImpl.java
  src/main/java/com/dnd/niceteam/security/UserDetailsServiceImpl.java
  src/main/java/com/dnd/niceteam/security/auth/controller/AuthController.java
  src/main/java/com/dnd/niceteam/security/auth/dto/AuthRequestDto.java
  src/main/java/com/dnd/niceteam/security/auth/dto/AuthResponseDto.java
  src/main/java/com/dnd/niceteam/security/auth/service/AuthService.java
  src/main/java/com/dnd/niceteam/security/exception/RefreshTokenIsNullException.java
  src/main/java/com/dnd/niceteam/security/exception/TokenInvalidException.java
  src/main/java/com/dnd/niceteam/security/exception/UsernameNotFoundException.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtAuthenticationCheckFilter.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtTokenProvider.java
  src/main/resources/application-jwt.yml
  src/test/java/com/dnd/niceteam/common/CommonDocsControllerTest.java
  src/test/java/com/dnd/niceteam/security/AuthApiTest.java
Labels: Status: Review Needed, Type: Improvement, Priority: High, Status: On Hold

#12 feature#2-2 JWT 인증 필터 빈 등록 및 로그아웃 구성
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/niceteam/security/SecurityConfig.java
  src/main/java/com/dnd/niceteam/security/UserDetailsServiceImpl.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtLogoutHandler.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtLogoutSuccessHandler.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtTokenProvider.java
  src/main/resources/application-db.yml
  src/test/java/com/dnd/niceteam/security/AuthApiTest.java
Labels: Type: Improvement, Priority: Medium, Status: Available

#16 Feature/#14 Member Aggregate 도메인 생성 및 프로젝트 세팅 업데이트
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dnd/niceteam/common/Domain.java
  src/main/java/com/dnd/niceteam/common/dto/ApiResult.java
  src/main/java/com/dnd/niceteam/domain/account/Account.java
  src/main/java/com/dnd/niceteam/domain/account/AccountRepository.java
  src/main/java/com/dnd/niceteam/domain/code/Field.java
  src/main/java/com/dnd/niceteam/domain/code/FieldCategory.java
  src/main/java/com/dnd/niceteam/domain/code/Personality.java
  src/main/java/com/dnd/niceteam/domain/code/TagReview.java
  src/main/java/com/dnd/niceteam/domain/common/BaseEntity.java
  src/main/java/com/dnd/niceteam/domain/common/BaseTimeEntity.java
  src/main/java/com/dnd/niceteam/domain/department/Department.java
  src/main/java/com/dnd/niceteam/domain/department/DepartmentRepository.java
  src/main/java/com/dnd/niceteam/domain/emailauth/EmailAuth.java
  src/main/java/com/dnd/niceteam/domain/emailauth/EmailAuthRepository.java
  src/main/java/com/dnd/niceteam/domain/member/Member.java
  src/main/java/com/dnd/niceteam/domain/member/MemberInterest.java
  src/main/java/com/dnd/niceteam/domain/member/MemberRepository.java
  src/main/java/com/dnd/niceteam/domain/memberscore/MemberScore.java
  src/main/java/com/dnd/niceteam/domain/memberscore/MemberScoreRepository.java
  src/main/java/com/dnd/niceteam/domain/university/University.java
  src/main/java/com/dnd/niceteam/domain/university/UniversityRepository.java
  src/main/java/com/dnd/niceteam/error/ApiExceptionHandler.java
  src/main/java/com/dnd/niceteam/error/ExceptionAspect.java
  src/main/java/com/dnd/niceteam/error/dto/ErrorResponseDto.java
  src/main/java/com/dnd/niceteam/error/exception/ErrorCode.java
  src/main/java/com/dnd/niceteam/member/domain/Member.java
  src/main/java/com/dnd/niceteam/member/domain/Role.java
  src/main/java/com/dnd/niceteam/member/repository/MemberRepository.java
  src/main/java/com/dnd/niceteam/member/service/MemberService.java
  src/main/java/com/dnd/niceteam/security/SecurityConfig.java
  src/main/java/com/dnd/niceteam/security/UserDetailsServiceImpl.java
  src/main/java/com/dnd/niceteam/security/auth/controller/AuthController.java
  src/main/java/com/dnd/niceteam/security/auth/dto/AuthResponseDto.java
  src/main/java/com/dnd/niceteam/security/auth/service/AuthService.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/com/dnd/niceteam/security/jwt/JwtLogoutHandler.java
  src/main/resources/application-jwt.yml
  src/test/java/com/dnd/niceteam/common/CommonDocsController.java
  src/test/java/com/dnd/niceteam/common/CommonDocsControllerTest.java
  src/test/java/com/dnd/niceteam/security/AuthApiTest.java
  src/test/java/com/dnd/niceteam/security/JwtWebTest.java
Labels: Type: Feature, Priority: Medium, Status: Available
