Repository dnd-side-project/dnd-7th-2-backend, pull requests merged in 2022-09, with the labels that each got.

#118 feat: Test용 커스텀 ObjectMapper 추가
  src/main/java/com/dnd/niceteam/code/config/EnumMapperFactory.java
  src/main/java/com/dnd/niceteam/code/controller/CodeController.java
  src/main/java/com/dnd/niceteam/code/dto/EnumMapperValue.java
  src/main/java/com/dnd/niceteam/comment/dto/CommentCreation.java
  src/main/java/com/dnd/niceteam/domain/code/ActivityArea.java
  src/main/java/com/dnd/niceteam/domain/code/DayOfWeek.java
  src/main/java/com/dnd/niceteam/domain/code/Field.java
  src/main/java/com/dnd/niceteam/domain/code/FieldCategory.java
  src/main/java/com/dnd/niceteam/domain/code/Personality.java
  src/main/java/com/dnd/niceteam/domain/code/ReviewTag.java
  src/main/java/com/dnd/niceteam/domain/code/VoteType.java
  src/main/java/com/dnd/niceteam/domain/common/EnumMapperType.java
  src/test/java/com/dnd/niceteam/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/dnd/niceteam/bookmark/controller/BookmarkControllerTest.java
  src/test/java/com/dnd/niceteam/code/config/EnumMapperFactoryTest.java
  src/test/java/com/dnd/niceteam/comment/controller/CommentControllerTest.java
  src/test/java/com/dnd/niceteam/common/jackson/RestDocsObjectMapper.java
  src/test/java/com/dnd/niceteam/common/jackson/TestEnumMapperSerializer.java
  src/test/java/com/dnd/niceteam/emailauth/controller/EmailAuthControllerTest.java
  src/test/java/com/dnd/niceteam/member/controller/MemberControllerTest.java
  src/test/java/com/dnd/niceteam/project/controller/ProjectControllerTest.java
  src/test/java/com/dnd/niceteam/recruiting/controller/RecruitingControllerTest.java
  src/test/java/com/dnd/niceteam/review/controller/MemberReviewControllerTest.java
  src/test/java/com/dnd/niceteam/security/AuthApiTest.java
  src/test/java/com/dnd/niceteam/security/JwtWebTest.java
  src/test/java/com/dnd/niceteam/vote/controller/VoteControllerTest.java
Labels: Type: Feature, Status: Review Needed, Priority: High

#119 Feature/#31 배포 세팅
  .gitignore
  src/main/resources/application-db.yml
  src/main/resources/application-jwt.yml
  src/main/resources/application.yml
  src/main/resources/data-mysql.sql
  src/main/resources/schema-mysql.sql
  src/test/java/com/dnd/niceteam/comment/controller/CommentControllerTest.java
  src/test/java/com/dnd/niceteam/recruiting/service/RecruitingServiceTest.java
  src/test/resources/application.yml
Labels: Priority: High

#122 fix(Applicant) : 지원현황 목록 조회 API 요청타입 수정
  src/main/java/com/dnd/niceteam/applicant/controller/ApplicantController.java
  src/main/java/com/dnd/niceteam/applicant/dto/ApplicantFind.java
  src/main/java/com/dnd/niceteam/applicant/service/ApplicantService.java
  src/test/java/com/dnd/niceteam/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/dnd/niceteam/applicant/service/ApplicantServiceTest.java
  src/test/java/com/dnd/niceteam/domain/recruiting/ApplicantRepositoryTest.java
Labels: Type: Bug, Priority: High
